### ISSUE TITLE
no type of install file/read me

### ISSUE THREAD

**Issue by TuffLuck** [kflorence/text-avenger#1]
Can you put up some kind of INSTALL/READ ME for someone that wishes to try it out that doesn't know it? Curious.

Is it something required to be uploaded to a web-server and opened from browser or opened from your desktop?

**Comment by kflorence** [comment]
@TuffLuck I'll try to throw something together soon. FYI this was built a pretty long time ago so I'm thinking it probably only works on Windows now.

**Comment by kflorence** [comment]
@TuffLuck so it appears the mac build of the game is too old to work on Mac OS X > 10.7 because it requires PowerPC application support. On windows, though, all you have to do is download the zip file, extract it, and run `game.exe` -- just tested it in a Windows 7 VM and it worked great.
